apiVersion: v2
name: aws-loadbalancer-controller
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

dependencies:
- name: aws-load-balancer-controller
  version: "1.3.3"
  repository: "https://aws.github.io/eks-charts"

